# Generated by Django 5.0.2 on 2024-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_alter_emotion_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='probability',
            field=models.IntegerField(null=True),
        ),
    ]
