# Generated by Django 5.0.2 on 2024-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0004_emotion_probability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='emotions',
            new_name='face_emotion',
        ),
        migrations.AddField(
            model_name='emotion',
            name='pose',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='emotion',
            name='voice_emotions',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
