# Generated by Django 5.0.2 on 2024-02-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0005_rename_emotions_emotion_face_emotion_emotion_pose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
