# Generated by Django 5.0.2 on 2024-02-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0009_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
