# Generated by Django 5.0.2 on 2024-03-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0010_plans_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
