# Generated by Django 5.0.2 on 2024-03-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0011_alter_emotion_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='probability',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
