# Generated by Django 5.0.2 on 2024-03-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0013_emailhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailHistory',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
