# Generated by Django 5.0.2 on 2024-03-03 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0014_emailhist_delete_emailhistory_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
