# Generated by Django 5.0.2 on 2024-03-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0016_remove_emotion_pose_pose'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhist',
            name='probability',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
