# Generated by Django 5.0.2 on 2024-03-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0017_emailhist_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailhist',
            name='probability',
        ),
        migrations.AddField(
            model_name='pose',
            name='probability',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
